const menuList=[{
        title:"首页",
        key:"/home"
    },
    {
        title:"商品管理",
        key:"/products",
        children:[
            {
                title:"分类管理",
                key:"/category"
            },
            {
                title:"商品管理",
                key:"/product"
            }
        ]
    },
    {
        title:"店铺",
        key:"/shop",
        children:[
            {
                title:"店铺装修",
                key:"/decorate"
            },
            {
                title:"店铺设置",
                key:"/setting"
            }
        ]
    }
];
export default menuList;